const {
  levelUpColors,
  levelUpBorderRadius,
  levelUpKeyframes,
  levelUpAnimation,
  levelUpBoxShadow,
  levelUpBackgroundImage,
  levelUpFontSize,
  levelUpSpacing,
  levelUpZIndex,
} = require("./theme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  safelist: [
    // ── Responsive visibility (sidebar, bottom nav, layout) ──
    "hidden",
    "md:block",
    "md:flex",
    "md:hidden",
    "md:pb-6",
    "md:p-6",
    "md:opacity-0",
    "md:bottom-4",
    "md:left-auto",
    "md:max-w-sm",
    "md:right-4",
    "sm:flex",
    "sm:px-4",
    "sm:p-4",
    "sm:flex-row",
    "sm:justify-end",
    "sm:max-w-sm",
    "sm:space-x-2",
    "sm:text-left",
    // ── Accessibility ──
    "sr-only",
    "focus:not-sr-only",
    "focus:fixed",
    "focus:left-4",
    "focus:top-4",
    "focus:z-50",
    "focus:rounded-md",
    "focus:bg-primary",
    "focus:px-4",
    "focus:py-2",
    "focus:text-primary-foreground",
    "focus:shadow-lg",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-ring",
    "focus:ring-offset-2",
    // ── Sidebar structure (peer/group markers) ──
    "peer",
    "group",
    // ── Sidebar collapsible states ──
    "group-data-[collapsible=icon]:!size-8",
    "group-data-[collapsible=icon]:!p-0",
    "group-data-[collapsible=icon]:!p-2",
    "group-data-[collapsible=icon]:-mt-8",
    "group-data-[collapsible=icon]:hidden",
    "group-data-[collapsible=icon]:opacity-0",
    "group-data-[collapsible=icon]:overflow-hidden",
    "group-data-[collapsible=icon]:w-[--sidebar-width-icon]",
    "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4))]",
    "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4)_+2px)]",
    "group-data-[collapsible=offcanvas]:w-0",
    "group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)]",
    "group-data-[collapsible=offcanvas]:right-[calc(var(--sidebar-width)*-1)]",
    "group-data-[collapsible=offcanvas]:translate-x-0",
    "group-data-[collapsible=offcanvas]:after:left-full",
    "group-data-[collapsible=offcanvas]:hover:bg-sidebar",
    // ── Sidebar side (left/right) ──
    "group-data-[side=left]:-right-4",
    "group-data-[side=left]:border-r",
    "group-data-[side=right]:border-l",
    "group-data-[side=right]:left-0",
    "group-data-[side=right]:rotate-180",
    // ── Sidebar variant (floating/inset) ──
    "group-data-[variant=floating]:rounded-lg",
    "group-data-[variant=floating]:border",
    "group-data-[variant=floating]:border-sidebar-border",
    "group-data-[variant=floating]:shadow",
    "has-[[data-variant=inset]]:bg-sidebar",
    // ── Sidebar inset peer-data selectors ──
    "peer-data-[variant=inset]:min-h-[calc(100svh-theme(spacing.4))]",
    "md:peer-data-[variant=inset]:m-2",
    "md:peer-data-[variant=inset]:ml-0",
    "md:peer-data-[variant=inset]:rounded-xl",
    "md:peer-data-[variant=inset]:shadow",
    "md:peer-data-[state=collapsed]:peer-data-[variant=inset]:ml-2",
    // ── Sidebar menu button peer-data ──
    "peer-data-[active=true]/menu-button:text-sidebar-accent-foreground",
    "peer-data-[size=sm]/menu-button:top-1",
    "peer-data-[size=default]/menu-button:top-1.5",
    "peer-data-[size=lg]/menu-button:top-2.5",
    // ── Sheet/Dialog animation states ──
    "data-[state=open]:animate-in",
    "data-[state=open]:fade-in-0",
    "data-[state=open]:slide-in-from-left",
    "data-[state=open]:slide-in-from-right",
    "data-[state=open]:slide-in-from-top",
    "data-[state=open]:slide-in-from-bottom",
    "data-[state=open]:duration-500",
    "data-[state=closed]:animate-out",
    "data-[state=closed]:fade-out-0",
    "data-[state=closed]:slide-out-to-left",
    "data-[state=closed]:slide-out-to-right",
    "data-[state=closed]:slide-out-to-top",
    "data-[state=closed]:slide-out-to-bottom",
    "data-[state=closed]:duration-300",
    // ── Active states ──
    "data-[active=true]:bg-sidebar-accent",
    "data-[active=true]:font-medium",
    "data-[active=true]:text-sidebar-accent-foreground",
    "data-[state=open]:hover:bg-sidebar-accent",
    "data-[state=open]:hover:text-sidebar-accent-foreground",
    "data-[state=open]:bg-secondary",
    "data-[state=open]:opacity-100",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: levelUpColors,
      borderRadius: levelUpBorderRadius,
      keyframes: levelUpKeyframes,
      animation: levelUpAnimation,
      boxShadow: levelUpBoxShadow,
      backgroundImage: levelUpBackgroundImage,
      fontSize: levelUpFontSize,
      spacing: levelUpSpacing,
      zIndex: levelUpZIndex,
    },
  },
  plugins: [require("tailwindcss-animate")],
};
